<a href="https://colab.research.google.com/github/sumonkaz/AdmissionTest/blob/main/Lab1_0Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Getting Started with `numpy`

### Learning Outcomes

In this activity we practice how to

- create arrays objects in various ways including sampling random data with `numpy.random`
- apply operations to arrays
- select parts of an array via indexing
- draw scatter plots `matplotlib`

### Prerequisites

- A first look at the numpy [tutorial](https://numpy.org/devdocs/user/absolute_beginners.html)
- And Panda [tutorial](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)
## Introduction

In this unit we are mainly going to work with the following Python libraries:
1. `numpy` for numerical computations
2. `scipy` for some advanced scientific computing methods (not often)
3. `matplotlib` for plotting data
4. `scikit-learn` for machine learning tools

## Basic Array Creation, Shape, and Data Type



The most central concepts of `numpy` are `array` objects, which represent a regular grid of values with some common type and an index structure to access those values ([what is an array](https://numpy.org/devdocs/user/absolute_beginners.html#what-is-an-array)).

#### Task A: Create some Arrays

**Work through [how to create a basic array](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-create-a-basic-array) by trying out code in the cell below we already added the line to import the `numpy` module into our namespace. This is typically done by the following line, which makes all numpy types and functions available with the prefix `np`.**

In [ ]:
import numpy as np

You should now be familiar with the most elementary way to create a `numpy` array, i.e., via calling `numpy.array` directly with a nested Python iterable that describes the data of the array as in the following two examples.

In [ ]:
np.array([3, 1, 5])

array([3, 1, 5])

In [ ]:
np.array([[3, 1, 5],
          [1, 9, 2]])

array([[3, 1, 5],
       [1, 9, 2]])

Some other important ways to arrays are the functions

- `arange` that creates arrays with consecutve integers (similar to the Python built-in function `range`)
- `zeros` that creates an array with all zero-entries of the specified type and shape
- `ones` that creats an array with all one-entries of the specified type and shape
- `eye` which creates an array representing the unit matrix of desired dimensionality `p`, i.e., an array of shape `(p, p)` with `1`-entries on the diagonal and `0`-entries elsewhere. Also here the type can be varied.

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros(shape=(5, 2), dtype=bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Generating Random Data

To test machine learning methods we will often generate some random data. A random number can be created with `numpy` via the function `numpy.random.default_rng` as in the cell below. We typically prodive a random seed in our activities to make the output of the subsequent cells deterministic/reproducible.

In [ ]:
RNG = np.random.default_rng(seed=0)
RNG.random()

0.6369616873214543

Besides the basic `random`-method, a random number generator has a number of much more convenient methods to generate random outcomes for different use cases.

One important one is the `choice`-method, which generates a random selection of non-negative integers up to a maximum number (exclusive). The keyword argument `replace` determines whether this selection is sampled with our witout replacement.

In [ ]:
RNG.choice(10, size=10)

array([5, 2, 3, 0, 0, 0, 1, 8, 6, 9])

In [ ]:
RNG.choice(10, size=10, replace=False)

array([3, 1, 4, 7, 9, 5, 2, 0, 6, 8])

Another important random number generator method is [`multivariate_normal`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.multivariate_normal.html), which can be used to sample data from a [multivariate normal distribtion](https://en.wikipedia.org/wiki/Multivariate_normal_distribution).

### Task B: Sample from Multivariate Normal

**Complete the line below to sample 20 data points from a 2-dimensional multivariate normal distribution with the following mean vector and covariance matrix:**

\begin{equation*}
\boldsymbol{\mu} =
\begin{pmatrix}
0\\
0
\end{pmatrix}
\qquad
\boldsymbol{\Sigma} =
\begin{pmatrix}
1.0 & 0.7\\
0.7 & 1.0
\end{pmatrix}
\end{equation*}

In [ ]:
cov = np.array([[1.0, 0.7], [0.7, 1.0]])
x = # YOUR CODE HERE
x

## Selecting Portions of an Array

Once we have an array at hand, we can manipulate it various ways, most importantly via [indexing and slicing](https://numpy.org/devdocs/user/absolute_beginners.html#indexing-and-slicing).

#### Task C: Select Columns

**Refer to the above section of the tutorial to select the two individual columns of our `x`-array and store them into the variables `x0` and `x1`.**

Once you have completed the code below you can run it to plot the `x`-array in a scatter plot with `matplotlib`.

In [ ]:
from matplotlib import pyplot as plt

plt.figure(figsize=(5, 5))
x0 = # YOUR CODE HERE
x1 = # YOUR CODE HERE
plt.scatter(x0, x1, edgecolors='black')
plt.xlim(-2.5, 2.5)
plt.ylim(-2.5, 2.5)
plt.xlabel('$x_1$')
plt.ylabel('$x_2$')
plt.show()

You might have already discovered that you can use binary operations like `+`, `-`, and so on on arrays with matching dimensionality to create new arrays (resulting from carrying out the operation element-wise).

For example:

In [ ]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

In [ ]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

Interestingly, we can also combine operands of different shape. There are relatively complex rules for the validity of such expressions (the keyword here is [broadcasting](https://numpy.org/devdocs/user/absolute_beginners.html#broadcasting)), but in the simplest and most important case, we use a single value as one of the operands, which is then conceptually replicated to create an array that matches the shape of the other operand.

For example:

In [ ]:
np.array([2, 3, 4]) + 5

In [ ]:
np.eye(3) + 1

In [ ]:
-1*np.arange(4)

Importantly, this extends to logical operators. For instance, in the next cell we are creating a boolean array that contains true at all positions where the other operand has an entry of at least `4`.

In [ ]:
np.arange(8) >= 4

In [ ]:
(np.arange(12) % 3) == 0

With the logical "and" and "or" operators, `&` and `|`, we can use this concept to describe the results of complex Boolean conditions.

#### Task D: Complex Boolean Expression

**Write an expression that creates a Boolean numpy array with `True`-entries where the index is greater than $3$ and divisible by $2$ (and `False`) otherwise.**

In [ ]:
#YOUR CODE HERE

Finally, we can combine these Boolean expressions with indexing to select portions of arrays that satisfy certain conditions.

For instance below we select all columns of a matrix where the entry on row 1 is greater than the entry in row 0.

In [ ]:
a = np.array([[3, 2, 5], [1, 4, 6]])
a

In [ ]:
a[:, a[1, :] > a[0, :]]

### Task E: Select Data from Specific Quadrant

**Complete the code below to plot in a different color the part of our previously generated data that is in the fourth quadrant, i.e., where $x_0 < 0$ and $x_1>0$.**

In [ ]:
selected = # YOUR CODE HERE
plt.figure(figsize=(5, 5))
plt.scatter(x[~selected, 0], x[~selected, 1], edgecolors='black')
plt.scatter(x[selected, 0], x[selected, 1], color='red', edgecolors='black')
plt.xlim(-2.5, 2.5)
plt.ylim(-2.5, 2.5)
plt.xlabel('$x_1$')
plt.ylabel('$x_2$')
plt.show()

## Vectorised Computations

The main advantage of `numpy` is that it allows us to specify "vectorised" computations, i.e., instead of computing results element by element by an explicit Python-loop, we can specify the desired outcome as vector operation. This usually results in a tremendous speed-up.

To illustrate, let us consider the problem of computing the vector with maximum norm from a sample of multi-variate normal random vectors.

In [ ]:
x_large = RNG.multivariate_normal(mean=np.zeros(20), cov=np.eye(20), size=1000)
x_large

Naively, we can find the norm of all rows as follows.

In [ ]:
def norms_naive(x):
    n, p = x.shape
    res = np.zeros(n)
    for i in range(n):
        for j in range(p):
            res[i] += x[i, j]**2
        res[i] = res[i]**0.5
    return res

norms1 = norms_naive(x_large)
norms1


In [ ]:
time1 = %timeit -o norms_naive(x_large)
time1.average

#### Task F: Vectorise Norm Computation

**Write a single expression that computes the norms of all rows of `x_large`.**

Hint: Decompose the problem into three parts

1. Compute a matrix that contains all the entries of `x_large` squared
2. Compute a vector that contains all *row*-sums of the previous matrix (see [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) to learn how to sum along columns with the `axis`-parameter)
3. Compute the element-wise square-root of all entries of the vector computed in step 2

In [ ]:
norms2 = # YOUR CODE HERE
np.allclose(norms1, norms2)

Repeat your code here to time it.

In [ ]:
time2 = %timeit -o # YOUR CODE HERE
time2.average

Let us see how much slower the naive version is than the vectorised version to understand how crucial vectorisation is for efficient Python code:

In [ ]:
time1.average/time2.average

Having computed all the norms, we can plot a histogram of them.

In [ ]:
plt.hist(norms1, density=True)
plt.xlabel('$\|x\|$')
plt.ylabel('$p(\|x\|)$')
plt.show()

We see that the maximum norm has a value of around 7. We can use the following `numpy` functions to efficiently (i.e., without explicit Python loop) find the maximum value and the corresponding index of an array.

In [ ]:
np.max(norms1)

In [ ]:
np.argmax(norms1)